Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,11 +19,13 @@ jobs:
         with:
           python-version: '3.x'
 
-      - name: Install Dependencies
         run: |
-         python -m pip install --upgrade pip
-          pip install joblib pandas numpy matplotlib seaborn scikit-learn python-docx pdfkit wkhtmltopdf
-                    sudo apt-get install -y wkhtmltopdf
+          python -m pip install --upgrade pip
+          pip install joblib pandas numpy matplotlib seaborn scikit-learn python-docx pdfkit
+          
+          # Ensure wkhtmltopdf is installed
+          sudo apt-get update
+          sudo apt-get install -y wkhtmltopdf || exit 0  # Avoid stopping if this fails
 
       - name: Run czyszczenie_porównywanieModeli.py
         run: |
